### ISSUE TITLE
无法识别setup中的变量

### ISSUE THREAD

**Issue by zouh7** [woden0415/vue3-ts-setup-pug#2]
按照你上面的配置还是不能识别setup中的变量啊 而且clone你的代码上面也是一样的不能识别 是我需要配置什么插件吗

**Comment by woden0415** [comment]
重新更新了一个版本，解决了volar无法识别的问题。

我本地关于vue的插件只用了最新版本的 **Vue - Official**

![pug](https://github.com/user-attachments/assets/6bd390c5-8d3e-4e6d-99ce-4743ca013414)
![Snipaste_2024-07-24_00-11-24](https://github.com/user-attachments/assets/0ad6313e-34ce-4720-b3a6-b7ddea633fc9)

**Comment by woden0415** [comment]
> 按照你上面的配置还是不能识别setup中的变量啊 而且clone你的代码上面也是一样的不能识别 是我需要配置什么插件吗

修复点可以看我的评论，如果解决你的问题和我说一下，我关闭这个issue！

**Comment by zouh7** [comment]
抱歉现在才看见  我已经放弃了pug  刚刚试了一下还是不行  可能其他插件冲突吧  使用pug之后整个模板中没有任何提示 ts类型也没了 之前弄了好几天没弄好 就彻底放弃pug了 哈哈哈 谢谢你

**Comment by H1jffff** [comment]
index.vue Doctor
❗ @vue/language-plugin-pug missing
For <template lang="pug">, the @vue/language-plugin-pug plugin is required. Install it using $ npm install -D @vue/language-plugin-pug and add it to vueCompilerOptions.plugins to support TypeScript intellisense in Pug templates.

package.json
{
  "devDependencies": {
    "@vue/language-plugin-pug": "latest"
  }
}
tsconfig.json / jsconfig.json
{
  "vueCompilerOptions": {
    "plugins": [
      "@vue/language-plugin-pug"
    ]
  }
}
Have any questions about the report message? You can see how it is composed by inspecting the [source code](https://github.com/vuejs/language-tools/blob/master/extensions/vscode/src/features/doctor.ts).
